version: '3'

networks:
  default:
    driver: bridge

services:
  postgres:
    image: 'postgres:14-alpine'
    networks:
      - default
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test

  benchmarker:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    depends_on:
      - postgres
    links:
      - postgres  