on:
  push:
    branches:
      - master
      - main

name: Generate Results
jobs:
  Results:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: 'postgres:latest'
        ports:
          - '5432:5432'
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Generate Results
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          .github/run_benchmarks_actions.sh > results.md
          git add results.md
          git commit -am "Generate benchmark results automatically."
          git push